name: sniffdog
base: core22
version: "1.1"

summary: Simple GUI Packet Sniffer
description: |
  SniffDog is a lightweight packet sniffer built with
  Python, Tkinter and Scapy.

grade: stable
confinement: classic

apps:
  sniffdog:
    command: launch-sniffdog

parts:
  sniffdog:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-tk
      - python3-scapy
